# Site settings
title: Silicon Babylon
email: bnmiller@gmail.com
description: "In the valley of many languages stacked to the heavens"
baseurl: ""
url: "http://www.siliconbabylon.com"

# Build settings
markdown: kramdown
permalink: pretty
