# Site settings
title: Silicon Babylon
email: bnmiller@gmail.com
description: "One voice in a valley of many languages stacked to the heavens"
baseurl: ""
url: "http://www.siliconbabylon.com"

# Build settings
markdown: kramdown
  input: GFM
permalink: pretty
